### ISSUE TITLE
is there a way for this plugin to cite blocks in logseq?

### ISSUE THREAD

**Issue by flashlight123** [haydenull/logseq-plugin-excalidraw#5]
as stated in the title, it would be perfect if we can cite blocks in this plugin.
The official whiteboard interface is not as aesthetically pleasing, and it would be perfect to have the functionality of the official whiteboard with the UI of Excalidraw.
do you have any plan on this? thanks!

**Comment by haydenull** [comment]
Thank you for the suggestion. Currently, our development plan is to complete the dashboard.

The purpose of the plugin is to avoid modifying Excalidraw as mush as possible, so that it can be keep up to date with the latest updates.

Therefore, the feature of cite logseq block may not be added. We believe that the official whiteboard will become better and better.
