### ISSUE TITLE
[ Feature Req ] .  ExcaliBrain  Logseq Version

### ISSUE THREAD

**Issue by Slabhub** [haydenull/logseq-plugin-excalidraw#7]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

linking blocks and pages from current graph  to all shape ...
Example obsidian excalibrain plugin
https://github.com/zsviczian/excalibrain

### Reproduce the Bug

...

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Thank you for the suggestion. 

The purpose of the plugin is to avoid modifying Excalidraw as mush as possible, so that it can be keep up to date with the latest updates.

This plugin is only for managing and using excalidraw in logseq. Perhaps you can  seek help from logseq team, or you can modify this project freely based on it.
